-- phpMyAdmin SQL Dump
-- version 3.4.11.1
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tiempo de generación: 12-10-2013 a las 08:03:16
-- Versión del servidor: 5.5.34
-- Versión de PHP: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `oriuspan_soluciones`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `cultivos`
--

DROP TABLE IF EXISTS `cultivos`;
CREATE TABLE IF NOT EXISTS `cultivos` (
  `cultivo_id` int(11) NOT NULL AUTO_INCREMENT,
  `cultivo_name` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`cultivo_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Volcado de datos para la tabla `cultivos`
--

INSERT INTO `cultivos` (`cultivo_id`, `cultivo_name`) VALUES
(1, 'Agricola'),
(2, 'Acuicola'),
(3, 'Pecuaria'),
(4, 'Manejo Ambiental');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `problemas`
--

DROP TABLE IF EXISTS `problemas`;
CREATE TABLE IF NOT EXISTS `problemas` (
  `pro_id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_name` text NOT NULL,
  `pro_sol` text NOT NULL,
  `pro_causa` text NOT NULL,
  `pro_cyc` text NOT NULL,
  `pro_img` varchar(100) NOT NULL DEFAULT '',
  `pro_cultivo_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pro_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=53 ;

--
-- Volcado de datos para la tabla `problemas`
--

INSERT INTO `problemas` (`pro_id`, `pro_name`, `pro_sol`, `pro_causa`, `pro_cyc`, `pro_img`, `pro_cultivo_id`) VALUES
(1, 'Suelos Agrícolas con disminución de su fertilidad y de su productividad.', 'Enriquecer y mejorar el suelo con la fracción biológica, mejorar la fracción orgánica del suelo y la fertilidad al digerir o bio transformar las hojas, tallos, raíces, frutos (subproductos de cosecha) que quedan en el campo después de la recolección de las cosechas, mejorar la formación de raíces al limpiar el suelo de fermentos y de toxinas,  mejorar la disponibilidad y la asimilación de nutrientes. Agregar un Abono Orgánico digerido para mejorar la fracción orgánica del suelo y la fertilidad, haciendo disponibles rápidamente los nutrientes para el nuevo cultivo. Disminuir los hospederos e inoculos de las enfermedades que aumentan en el suelo con el mismo cultivo.', 'Alta extracción de nutrientes del suelo para producir cada cosecha. No se le retorna al suelo los nutrientes que le entrego al cultivo para producir la cosecha. Con las cosechas, los cultivos necesitan mas fertilizantes para crecer y producir. El suelo se deteriora en fertilidad y en estructura.', 'Aplicar 1,0 a 1,5 Litros por hectárea de <B>BACTHON</B> en aspersión dirigido al suelo antes de la preparación, antes o después de la siembra. También se aplica en drencho o en el sistema de riego.', 'bacthon', 1),
(2, 'Alta Compactación del suelo con dificultad en la formación de raíces y baja productividad', 'Mejorar el suelo, la fracción orgánica del suelo y la fertilidad al digerir o bio transformar las hojas, tallos, pseudotallos, raíces, frutos (subproductos de cosecha) que quedan sobre el suelo en el campo después de la recolección de las cosechas, mejorar la formación de raíces al limpiar el suelo de fermentos y de toxinas,  mejorar la disponibilidad y la asimilación de nutrientes. Agregar un Abono Orgánico digerido para mejorar la fracción orgánica del suelo y la fertilidad, haciendo disponibles rápidamente los nutrientes para el nuevo cultivo. ', 'Alta perdida de la fracción orgánica del suelo por la alta extracción de nutrientes para obtener las cosechas afectando su fertilidad y la estructura. No se le devuelve al suelo la fracción orgánica que usa el cultivo para crecer y producir. El suelo se deteriora con muchas cosechas. La compactación no permite una buena formación de raíces para la asimilación de nutrientes con baja productividad o alto uso de fertilizantes químicos.', 'Aplicar en aspersión dirigido al suelo antes de la preparación o antes o después de la siembra. También se aplica en drench o en el sistema de riego. <B>BACTHON</B> 1 a 1.5 L/haAplicar en aspersión dirigido al material vegetal bien picado después de las podas o raleos. <B>BACTHON</B> 1 a 2 L/ha', 'bacthon', 1),
(3, 'Alto incremento de lodos en el fondo del estanque hasta formar una capa gruesa y con fuerte olor a descomposición. ', 'Digerir o Bio Transformar los lodos que se depositan en el fondo del estanque que contienen alimento, deyecciones, cadáveres, depositos orgánicos, para limpiar el estanque y evitar incremento de toxinas, amonios, nitritos, sulfuros, metanos en solución y patógenos que enferman la población en crecimiento de Camarones y Peces. Se obtiene al final del ciclo productivo un fondo &quot;limpio&quot; sin grandes depósitos de lodos.', 'Alta acumulación de depósitos orgánicos en los fondos, por alimento no consumido, cadáveres, deyecciones, depósitos orgánicos que vienen en las aguas de recambio, que incrementan la concentración tóxica en los fondos, que no se transforman y se descomponen hasta formar toxinas que causan la muerte a los Camarones y Peces cuando llegan al estanque en el nuevo ciclo y además se vuelven hospederos de patógenos que incrementan la mortalidad en primeros estados de cultivo.', 'Aplicar 1 a 2 Litros de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio2-h-25-sc" TARGET="_blank"><B><U>BIO2-H</U></B></A><B> </B>por hectárea de superficie diluido en agua al ingreso del estanque en el momento de iniciar el nuevo cultivo con baja columna de agua o con el sistema de flauta al fondo del estanque antes de adicionar los Camarones o Peces.Repetir cada 15 días aplicando 250 cc de <B><U>BIO2-H</U></B> por hectarea de superficie de agua.', 'bio2h', 2),
(6, 'Incremento de la cantidad de fertilizantes usados por la disminución de la productividad.', 'Incrementar la eficacia en la asimilación de los fertilizantes en un 15% o más, limpiando el suelo de toxinas para mejorar la formación de raíces, mejorar la disponibilidad y la asimilación de nutrientes para las plantas.', 'Suelos con alta carga de alcoholes, amoniacos, toxinas, metanos, sulfuros, sales que fijan los fertilizantes. Baja cantidad de nutrientes disponibles en el suelo. Baja formación de raíces para nutrición y soporte en la planta. Baja eficacia en la asimilación de los nutrientes.', 'Aplicar 1,0 a 1,5 Litros por hectárea de <B>BACTHON</B> en aspersión dirigido al suelo después de la aplicación de los fertilizantes. También se aplica en drench o en el sistema de riego.', 'bacthon', 1),
(7, 'Alta cantidad de hojas, tallos, pseudotallos, frutos, raíces (Subproductos) que quedan sobre el suelo después de la cosecha o se incorporan al suelo, que se descomponen y fermentan dañando las raíces del próximo cultivo y el suelo, disminuyendo la capacidad de la planta para nutrirse, se fijan los nutrientes en el suelo y los abonos, se hace más susceptible el cultivo a las enfermedades y a los insectos plaga.', 'Digerir o Bio Transformar rápidamente las hojas, tallos, pseudotallos, raíces, frutos (subproductos de cosecha) que quedan en el campo después de la recolección de las cosechas, para convertirlos en suelo mejorando la fracción orgánica y la fertilidad, limpiando de alcoholes, amoniacos y toxinas que se fijan en el suelo por la fermentación del material vegetal en descomposición y dañan las raíces y el suelo, mejorar la formación de raíces, la disponibilidad y asimilación de nutrientes.', 'Los subproductos o residuos de cosecha como hojas, tallos, pseudotallos, frutos y raíces, se descomponen y fermentan sobre el suelo y cuando se incorporan formando alcoholes, amoniacos, toxinas, metanos y sulfuros que afectan las raíces y el próximo cultivo. Se incrementan los hospederos de enfermedades y de insectos plaga. El tiempo para volver a usar el suelo en un nuevo cultivo es largo (3 a 4 meses o má</FONT>s). Cuando se queman se deja de usar unos nutrientes que le ayudan al suelo a mejorar su fracción orgánica y la fertilidad.', 'En cultivos semestrales aplicar en aspersión al suelo sobre toda la superficie: <B>BACTHON</B>: 1 a 1.5 L/haEn cultivos perennes aplicar en aspersión al suelo sobre toda la superficie repasando al pie de la planta: <B>BACTHON</B> 1 a 1.5L/haEn Piña post cultivo, se aplica en aspersión sobre la planta en pie antes de la triturada, picada o rastreada. A la semana una segunda aplicación después de la triturada, picada o rastreada. Luego se prepara el suelo: <B>BACTHON</B> 1.5 a 2 L/ha por 2 aplicaciones.Se puede aplicar en mezcla con los herbicidas en aspersión sobre toda la superficie del suelo: <B>BACTHON</B> 1 a 1.5 L/ha.Cuando hay podas o raleos aplicar sobre los subproductos orgánicos picados o triturados: <B>BACTHON</B> 1 a 1.5 L/ha.', 'bacthon', 1),
(9, 'El Monocultivo', 'Enriquecer y mejorar el suelo con la fracción biológica, mejorar la fracción orgánica del suelo y la fertilidad al digerir o bio transformar las hojas, tallos, raíces, frutos (subproductos de cosecha) que quedan en el campo después de la recolección de las cosechas, mejorar la formación de raíces al limpiar el suelo de fermentos y de toxinas, mejorar la disponibilidad y la asimilación de nutrientes. Agregar un Abono Orgánico digerido para mejorar la fracción orgánica del suelo y la fertilidad, haciendo disponibles rápidamente los nutrientes para el nuevo cultivo. Disminuir los hospederos e inoculos de las enfermedades que aumentan en el suelo con el mismo cultivo.', 'El uso del suelo con un solo cultivo desgasta el suelo por las necesidades continuas de los mismos nutrientes. Se compacta el suelo por el alto uso y la perdida de la fracción orgánica del suelo. Los suelos disminuyen la productividad y se seleccionan, especializan e incrementan las malezas, las enfermedades y los insectos plaga. ', 'Aplicar en aspersión dirigida al suelo 1,0 a 1,5 Litros por hectárea de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B>BACTHON </B></A>en mezcla con 300 gramos de <A HREF="http://whttp://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/tricho-d-wp" TARGET="_blank"><B>TRICHO-D</B></A> por hectárea, antes de la preparación, antes y después de la siembra. También se aplica en drench o en el sistema de riego.', 'bacthonTrichod', 1),
(12, 'Alta mortalidad de semillas y plantulas en semilleros, germinadores y almácigos. Baja germinación de semillas.', 'Proteger las semillas y plantulas contra enfermedades y patogénos en los semilleros, germinadores y almácigos, limpiar el sustrato de alcoholes y toxinas mejorando la formación de raíces, la asimilación de nutrientes y colonizar las raíces con una población benéfica antagonista para los patógenos.', 'Uso de sustratos contaminados para la siembra de los semilleros, germinadores y almácigos con patógenos, con alto contenido de alcoholes, amoniacos y toxinas que dificultan la formación de raíces, la nutrición y  debilitan las semillas y plantulas hasta la muerte por enfermedades. Poco uso de semillas certificadas. Alto uso de semillas con patógenos y de insectos plaga que afectan la germinación. Bajo uso de protectantes biológicos en la semilla.', 'Aplicar 2 cc de<B><U> </U></B><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B>BACTHON</B></A><B><U> </U></B>en mezcla con 1 gramo de <A HREF="http:/www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/tricho-d-wp" TARGET="_blank"><B>TRICHO-D WP</B></A> por kilo de semilla diluidos en 15 cc de Agua en aspersión sobre la semilla antes de la siembra o en la línea de la planta procesadora de la semilla.  Aplicar 10 cc de<B> </B><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B>BACTHON SC</B></A><B> </B></FONT>por Litro de Agua (200 cc por bomba de 20 Litros), en mezcla con 3 gramos de<B> </B><A HREF="http:/www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/tricho-d-wp" TARGET="_blank"><B>TRICHO-D WP</B></A></FONT> por Litro de Agua (60 gramos por bomba de 20 Litros), en aspersión dirigido al suelo del semillero, germinador o el almácigo a la siembra o al transplante, cada semana hasta el trasplante.', 'bacthonTrichod', 1),
(15, 'Suelos con varias cosechas de pastos, en ocasiones con sobrepartoreo, con hojas, tallos, raices de las cosechas anteriores sin digerir sobre y dentro del suelo, con fermentación y alto contenido de alcoholes y toxinas en el suelo que no dejan formar las raices y crecer las plantas del proximo pastoreo. Olores fuertes. ', 'Digerir o Bio Transformar rápidamente los residuos de pastos que quedan sobre el suelo después del pastoreo, para convertirlos en suelo mejorando la fracción orgánica y la fertilidad, limpiar de alcoholes, amoniacos y toxinas que se fijan en el suelo por la fermentación del material vegetal en descomposición, mejorar la formación de raíces, la disponibilidad y asimilación de nutrientes.', 'Alta acumulación de residuos de pastos sobre el suelo por pasturas no consumidas o pisoteadas, deyecciones,  no se transforman y se descomponen hasta formar toxinas, alcoholes, amoniacos que causan la muerte de las raíces nuevas y debilita la recuperación. Plantas de pasto muy debiles, bajo macollamiento.', 'Aplicar en aspersión al suelo 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B><U>BACTHON</U></B></A> en mezcla con 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bio-q-sc" TARGET="_blank"><B><U>BIO-Q</U></B></A>, máximo 7 días después del pastoreo o en mezcla con el  herbicida.', 'bacthonBioq', 3),
(26, 'Baja formación de raíces en semilleros. germinadores y almacigos o en el campo después de la siembra.', 'Limpiar el suelo donde crecen las raíces de la planta y mejorar  biológicamente la formación de raíces para fortalecer la disponibilidad y asimilación de los nutrientes, mejorar la nutrición, mejorar el desarrollo de las plántulas y la fortaleza cuando llegue al campo.Recuperar la formación de raíces cuando hay daños por alto contenido de fermentos y toxinas en el campo, daños por nematodos o insectos plaga. ', 'Sustratos usados para sembrar las semillas o plantulas con origen diverso que se fermenta y restringe la formación de raíces en esta etapa muy importante del cultivo. Bajo vigor de las semillas.Alto contenido de fermentos y toxinas en el suelo que daña y quema las raíces nuevas en el cultivo establecido, daños por nematodos y por insectos plaga.', 'Aplicar 10 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/buen-suelo-sc" TARGET="_blank"><B>BUENSUELO </B></A>por Litro de Agua (200 cc por bomba de 20 Litros), en aspersión dirigido al suelo del semillero, germinador o el almácigo a la siembra o al transplante y cada semana hasta el trasplante.Aplicar 1,0 a 1,5 Litros de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/buen-suelo-sc" TARGET="_blank"><B>BUENSUELO </B></A></FONT>en aspersión o en drench o en el sistema de riego dirigido al suelo cuando se detecte mala formación de raíces o daños por Nematodos o Insectos Plaga.', 'buensuelo', 1),
(28, 'Incremento de enfermedades en el suelo que enferman el cultivo.', 'Digerir la materia orgánica que está en el suelo que sirve de hospedero. Incrementar los antagonistas naturales de los fitopatógenos para disminuir la cantidad del inóculo que causa las enfermedades. Sanitizar el suelo.<B>SUELO SANO, CULTIVO SANO!!!</B>', 'Alta población de enfermedades en el suelo y alta cantidad de hospederos (materia orgánica sin digerir) que incrementa el inóculo en el cultivo.Incremento constante del inóculo en el suelo agrícola cosecha a cosecha. Mas enfermedades con el tiempo.', 'Aplicar 300 a 600 gramos por hectárea de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/tricho-d-wp" TARGET="_blank"><B>TRICHO-D </B></A>en mezcla con 1 a 1.5 L/ha de <B>BACTHON,</B> en aspersión, en drench o en el sistema de riego, dirigido al suelo antes o después de la siembra.', 'bacthonTrichod', 1),
(29, 'Incremento de enfermedades en las hojas, flores y frutos del cultivo.', 'Proteger las hojas, ramas, flores y frutos con antagonistas de las enfermedades para prevenir que causen las enfermedades con daño económico para el cultivo y la producción.', 'Alto inóculo de las enfermedades en el cultivo </FONT>porque hay hospederos en el suelo que emiten constantemente las esporas que causan la enfermedad e infectan las hojas, flores y frutos.Alta susceptibilidad del cultivo a las enfermedades por desbalances en nutrición.  ', 'Aplicar 300 a 600 gramos por hectárea de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bio-fungo-wp" TARGET="_blank"><B>BIOFUNGO </B></A>en aspersión foliar dirigido a los tallos, hojas y frutos.', 'biofungo', 1),
(30, 'Alto daño de raíces por Nematodos y por Insectos Plaga con muerte de las plantas, volcamiento y disminución de la producción.', 'Proteger las raíces del cultivo aumentando y colonizando con antagonistas naturales de nematodos y de insectos plaga. Limpiar el suelo de alcoholes y toxinas para fortalecer la formación de raices nuevas. ', 'Incremento de la población de Nematodos por la resistencia al control químico y el incremento poblacional por disminución de los antagonistas naturales. Alto daño de las raíces que causa volcamiento, muerte de las plantas y disminución de la producción.', 'Aplicar 100 a 300 gramos por hectárea de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/micosplag" TARGET="_blank"><B>MICOSPLAG WP</B></A><B> </B>en mezcla con 1,0 a 1,5 Litros de<B> </B><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/buen-suelo-sc" TARGET="_blank"><B>BACTHON </B></A>por hectérea en aspersión, en drench o en el sistema de riego dirigido a la base de la planta, en la gotera o cerca del lugar donde se encuentran las raíces.', 'micosplag', 1),
(31, 'Incremento de daños por Insectos Plaga en los cultivos.', 'Con Manejo Integrado aplicar las enfermedades de insectos en mezcla con un insecticida para controlar la población de insectos susceptibles que están haciendo daño y los insectos resistentes se enferman incrementando el nivel de control y disminuyendo la cantidad de insectos plaga de resurgencia.', 'Una proporción alta de insectos plaga resistentes al control químico.Aumento de la incidencia de insectos plaga secundarias que se vuelven principales.Mayor capacidad de reproducción y alimentación por frecuentes aplicaciones de insecticidas químicos.Incremento de hospederos por cultivos frecuentes y mal manejo de subproductos de cosecha.', 'Aplicar 100 a 200 gramos por hectarea de <A HREF="../portal/content/view/24/36/" TARGET="_blank"><B>MICOSPLAG </B></A>en aspersión foliar antes de que se inicie el daño o supere el nivel de daño económico.En Manejo Integrado mezclar con un insecticida químico para &quot;controlar&quot; los insectos plaga susceptibles y el <A HREF="../portal/content/view/24/36/" TARGET="_blank"><B>MICOSPLAG </B></A></FONT>enferma la población que es resistente a la acción del insecticida. Así se incrementa el &quot;control&quot; y disminuye la siguiente generación de resurgencia, pues el <A HREF="../portal/content/view/24/36/" TARGET="_blank"><B>MICOSPLAG </B></A></FONT>bio regula la próxima generación.', 'micosplag', 1),
(32, 'Cultivos intoxicados con dificultad para recuperarse y nutrirse.', 'Recuperar y Desintoxicar el cultivo en forma inmediata con quelatos en aminoácidos que bloquean la acción del herbicida o la toxina y facilitan de nuevo el desarrollo y el crecimiento.', 'Uso de herbicidas con alto impacto en el cultivo. Algunos insectos plaga chupadores que inoculan toxinas a la planta.', 'Aplicar en aspersión foliar despues de la aplicación de los herbicidas y repetir a los 15 días.<B>Dosis: BIO-Q: </B>1 L/ha, <B>BIQTICON</B>: 1 L/ha', 'bioqBiqticon', 1),
(33, 'Cultivos con problemas de desarrollo, atrasados, con desbalances por mala nutrición, con estres por heladas, sequias, exceso de agua, enfermedades y daños por Insectos Plaga.', 'Balancear nutricionalmente el cultivo para recuperarlo en forma inmediata con quelatos en aminoácidos.Mejor desarrollo de la planta y mejor formación de tallos molinables en Caña.', 'Desbalance nutricional por deficiente asimilación de nutrientes o condiciones de estrés o dificultades para recuperarse. ', 'Aplicar en aspersión foliar despues del  evento y repetir a los 8 días si el problema persiste.<B>Dosis:</B> <B>BIO-Q:</B> 500 cc a 1 L/ha, <B>BIQTICON</B>: 500 cc a 1 L/ha.', 'bioqBiqticonEspigador', 1),
(34, 'Caida de flores y frutos, baja calidad y peso de los frutos.', 'Recuperar y Balancear el cultivo en forma inmediata con quelatos en aminoácidos que lo balancean nutricionalmente y estimulan la retención de las flores y frutos, el llenado, el peso y la calidad final.', 'Desbalance nutricional por deficiente asimilación de nutrientes o condiciones de estrés en las etapas criticas de formación de flores y frutos.', 'Aplicar en aspersión foliar en prefloración o floración o llenado de fruto.<B>Dosis: BIO-Q</B>: 500 cc a<B> </B>1 L/ha, <B>ESPIGADOR</B>: 500 cc a 1 L/ha', 'bioqBiqticonEspigador', 1),
(35, 'Baja productividad con altos costos.', 'Se debe conocer y atacar la causa del problema. Anticiparse con prevención evita altos costos de control.', 'Se controlan los problemas sin analizar la causa. Esto exige un uso continuo en controlar la consecuencia.', 'La solución al problema desde la causa se aplica antes de que sucedan los problemas. Si se presenta el problema se debe controlar y después balancear con nuestras soluciones.', 'propuestaOrius', 1),
(36, 'Alta cantidad de toxinas en el fondo del estanque que al inicio del ciclo productivo pueden causar mortalidad en los Camarones y Peces. ', 'Digerir o Bio Transformar muy rápidamente las toxinas que afloran desde los lodos en el nuevo cargue antes de agregar los nauplios o alevinos y facilitar el establecimiento de la población nueva que llega susceptible a sufrir un impacto con descompensación que le puede causar la muerte.', 'Alta concentración de toxinas, amonios, metanos, sulfuros y nitritos en el fondo del estanque por una gruesa capa de depósitos orgánicos del ciclo productivo anterior. Cuando se adicionan los Camarones o Peces hay intoxicación, falta de oxigeno y muerte.', 'Aplicar 1 a 2 Litros de<U> </U><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-clean-sc" TARGET="_blank"><B><U>BIOCLEAN</U></B></A><U> </U>por hectárea de superficie de agua, diluido en agua al ingreso al estanque o con el sistema de flauta en el momento de iniciar el nuevo cultivo antes de adicionar los Camarones o Peces para el nuevo ciclo productivo.', 'bioclean', 2),
(37, 'Alta concentración de amonios, nitritos y nitratos en la solución del agua que intoxican los Camarones y Peces. ', 'Rápido desdoblamiento de las moléculas orgánicas y las nitrogenadas hasta liberar el Nitrógeno y &quot;limpiar&quot; el agua para que se suelte el oxigeno y puedan disponerlo muy bien los Camarones y Peces.', 'Deyección de los Camarones o Peces, dilución de los alimentos agregados, alta carga orgánica de las aguas de recambio, alta concentración de Amonios, Nitritos y Nitratos en la solución del agua, baja población de microorganismos benéficos que transformen las moléculas nitrogenadas y orgánicas.', 'Aplicar 1 a 2 Litros de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio2-h-25-sc" TARGET="_blank"><B><U>BIO2-H</U></B></A> por hectárea de superficie de Agua diluido en agua al ingreso al estanque o en aspersión en superficie cuando se presentan altas concentraciones de Amonios, Nitritos y Nitratos.', 'bio2h', 2),
(38, 'Incremento de patógenos en el fondo del estanque por alta concentración orgánica en descomposición (alimento, heces, cadáveres, precipitados) que causan la muerte a Camarones y Peces por patógenos.', 'Digerir y Limpiar el fondo del estanque y desdoblar la carga orgánica que esta en la solución del agua que cuando se incrementa, consume oxigeno y facilita la susceptibilidad enfermedades.', 'Incremento del inoculo de patógenos por la cantidad de lodos en el fondo y el material orgánico en descomposición que sirven de hospederos e incrementan la población patogénica que enferma los Camarones y Peces.', 'Aplicar 1 a 2 Litros de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio2-h-25-sc" TARGET="_blank"><B><U>BIO2-H </U></B></A>por hectárea de superficie de agua diluido en agua al ingreso al estanque o en aspersión en superficie o con el sistema de flauta en el fondo del estanque.', 'bio2h', 2),
(39, 'Eventos no esperados que causan mortalidades en etapas criticas de crecimiento. ', 'Limpiar rápidamente el fondo del estanque de las toxinas y recuperar fortaleciendo la población de Camarones y Peces para evitar el incremento de la mortalidad.', 'Incremento de la concentración de toxinas en solución en la interfase entre el fondo y los lodos con alto incremento de patógenos anaeróbicos.', 'Aplicar 1 Litro de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-clean-sc" TARGET="_blank"><B><U>BIOCLEAN</U></B></A> y 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"><B><U>BIOAQUA</U></B></A> por hectarea de superficie de agua en aspersión en superficie. El 30% de la solución se puede aplicar al fondo con el sistema de flauta.', 'biocleanBioaqua', 2),
(40, 'Disminución del plancton nativo con dificultades de establecimiento de los Camarones y Peces en el nuevo ciclo de cultivo.', 'Incrementar la población nativa de Plancton para colonizar muy rápidamente las aguas y estimular la nutrición con balance en la nueva población de Camarones y Peces.', 'Uso de enmiendas minerales y orgánicas, fertilizantes químicos y algunos químicos que causan un desbalance en el fondo del estanque e incrementa la susceptibilidad a las enfermedades y el crecimiento de organismos no deseados que colonizan el fondo, la interfase y la solución del agua consumiendo nutrientes y oxigeno causando un desbalance nutricional severo.', 'Aplicar 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"><B><U>BIOAQUA</U></B></A> por hectárea de superficie de agua diluido en agua al ingreso al estanque o en aspersión en superficie.', 'bioaqua', 2),
(41, 'Baja asimilación del alimento en los Camarones y Peces. ', 'Incrementar la base nutricional estimulando la producción de Plancton y facilitando la transformación del alimento para mejor disponibilidad y asimilación.Incrementar la población de nutrientes beneficos en la solución del agua', 'Baja capacidad de los Camarones y Peces de tomar los nutrientes por bajo estimulo nutricional y dificultad en la digeribilidad del alimento.', 'Aplicar 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"><B><U>BIOAQUA</U></B></A><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"> </A>por hectarea de superficie de agua diluido en agua al ingreso al estanque o en aspersión en superficie.Para aumentar la digeribilidad del alimento en el tracto digestivo se usa 1 Litro de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"><B><U>BIOAQUA</U></B></A><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-aqua-sc" TARGET="_blank"> </A></FONT>en mezcla con 1 Litro de<A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-clean-sc" TARGET="_blank"> </A><A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-clean-sc" TARGET="_blank"><B><U>BIOCLEAN</U></B></A> para 4 Toneladas de balanceado.', 'bioaqua', 2),
(42, 'Baja productividad con altos costos.', 'Se debe conocer y atacar la causa del problema. Anticiparse con prevención evita altos costos de control.', 'Se controlan los problemas sin analizar la causa. Esto exige un uso continuo en controlar la consecuencia.', 'La solución al problema desde la causa se aplica antes de que sucedan los problemas. Si se presenta el problema se debe controlar y después balancear con nuestras soluciones.', 'propuestaOrius', 2),
(43, 'Pasturas en suelos con baja fertilidad, poca productividad, las plantas de pastos no responden, baja formación de raíces, alto uso de fertilizantes quimicos y minerales.', 'Enriquecer, limpiar y recuperar el suelo para mejorar la formación de raíces y mejorar la disponibilidad y asimilación de nutrientes para las plantas.</FONT> Incrementar la eficacia en la asimilación de los fertilizantes químicos, orgánicos y minerales en un 15% o más. ', 'Suelos con cosechas continúas de forraje y disminución de la fertilidad del suelo que dificulta el establecimiento y crecimiento de la nueva cosecha de pastos. Incremento en los suelos </FONT>de la carga de alcoholes, amoniacos, toxinas, sales, por la descomposición de los residuos del pastoreo, que fijan los fertilizantes. Baja cantidad de nutrientes disponibles en el suelo. Baja formación de raíces para nutrición y soporte en la planta. Baja eficacia en la asimilación de los nutrientes.', 'Aplicar en aspersión dirigido al suelo 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B><U>BACTHON </U></B></A>en mezcla con 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B><U>BIO-Q</U></B></A>, 7 días después del pastoreo o después de la fertilización.', 'bacthonBioq', 3),
(44, 'Suelos con pasturas que son aplicados constantemente con abonos orgánicos o estiércoles líquidos que muestran amarillamientos y crecimientos lentos. Tienen problemas de moscas. ', 'Digerir los subproductos orgánicos frescos para evitar que continúen produciendo fermentos, &quot;limpiar&quot; el suelo y bio transformar la materia orgánica a suelo mejorando la fertilidad y productividad de forraje.', 'Uso de estiércoles líquidos o abonos orgánicos no digeridos aplicados a las pasturas que generan fermentación con emisión de alcoholes, toxinas y amoniacos e intoxican el cultivo de pastos. Las moscas se reproducen en el material orgánico fresco en descomposición. Baja formación de raíces. Muerte de plantas', 'Aplicar en aspersión dirigido al suelo, 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bacthon-sc" TARGET="_blank"><B><U>BACTHON</U></B></A> en mezcla con 500 cc de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/bio-q-sc" TARGET="_blank"><B><U>BIO-Q</U></B></A>, máximo 7 días después del pastoreo o después de la fertilización.', 'bacthonBioq', 3),
(45, 'Collaria sp (Chinche de los Pastos), Aeneolamia sp (Salivazo o Candelilla de los Pastos), que se presentan espontaneamente y son resistentes a los insecticidas quimicos con varias aplicaciones para controlarlas.', 'Manejo Integrado usando el <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/micosplag" TARGET="_blank"><B><U>MICOSPLAG</U></B></A> en mezcla con el insecticida para controlar los insectos plaga susceptibles al insecticida y el <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/micosplag" TARGET="_blank"><B><U>MICOSPLAG</U></B></A> para enfermar y bio regular los insectos plaga resistentes.', 'Aplicación frecuente de insecticidas para control que crean resistencia a las diferentes moléculas agroquímicas y se incrementa el daño por la capacidad de los insectos plaga de defenderse aumentando sus poblaciones muy rápidamente.', 'Aplicar en aspersión foliar 50 a 100 gramos de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/micosplag" TARGET="_blank"><B><U>MICOSPLAG</U></B></A> en Manejo Integrado en mezcla con el insecticida cuando se inicie el daño económico  a la pastura.', 'micosplag', 3),
(46, 'Baja productividad con altos costos.', 'Se debe conocer y atacar la causa del problema. Anticiparse con prevención evita altos costos de control.', 'Se controlan los problemas sin analizar la causa. Esto exige un uso continúo en controlar la consecuencia.', 'La solución al problema desde la causa se aplica antes de que sucedan los problemas. Si se presenta el problema se debe controlar y después balancear con nuestras soluciones.', 'propuestaOrius', 3),
(47, 'Estiércoles que causan impacto ambiental y que necesitan un manejo ordenado. ', 'Acumular los estiércoles para digerirlos ordenadamente hasta convertirlos en un excelente Abono Orgánico que se usa para los cultivos de pastos o cualquier otro cultivo agrícola. Así se evitan las moscas, otros insectos plaga y los malos olores.', 'Alta producción diaria de estiércol por animal que se maneja fresco en los sitios de producción y que si no se planea el manejo, se convierte en un problema ambiental y sanitario.', 'Para producir Abono Orgánico se usa 1 Litro de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/agricola/digestor-sc" TARGET="_blank"><B><U>DIGESTOR</U></B></A><B><U> </U></B>para 10 metros cúbicos de estiércol  con la tecnología de <B>ORIUS BIOTECNOLOGÍA</B> (Ver &quot;Como Producir un Excelente Abono Orgánico&quot;).', 'digestor', 3);
INSERT INTO `problemas` (`pro_id`, `pro_name`, `pro_sol`, `pro_causa`, `pro_cyc`, `pro_img`, `pro_cultivo_id`) VALUES
(48, 'Malos olores en los estercoleros con alta concentración de lodos en el fondo. ', 'Cuando el estiércol se lava y se agrega a un estercolero se debe manejar la fermentación para evitar malos olores y el impacto que causa este estiércol que se acidifica por la fermentación, los alcoholes, amoniacos, sulfuros y metanos.Retirar estos elementos tóxicos que están en la suspensión del estercolero, para que se inicie la digestión ordenada del estiércol y así retirar los malos olores, digerir los lodos que se depositan en el fondo y saturan los estercoleros y las piscinas de oxidación.', 'Alta concentración de toxinas que no permite avanzar con la digestión orgánica y se acumula en los fondos de los depósitos o estercoleros hasta que se saturan, emitiendo olores muy fuertes y líquidos con alta carga orgánica y ácida.', 'Diluir 1 Litro de<A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio2-h-25-sc" TARGET="_blank"> </A><B>MAXCLEAN</B> en 200 Litros de agua por deposito o estercolero.<FONT KERNING="0"></FONT>Se aplica gota a gota colocando  un gripo en el parte inferior de la caneca de 200 L y descargar  50 cc/minuto de la solución directamente en el estercolero, minimo durante 4 horas diarias y preferiblemente cuando se realice el lavado de las instalaciones donde está el estiércol. <FONT KERNING="0"></FONT>', 'digestor', 3),
(49, 'Alta concentración de sabores no esperados al final del ciclo y con rechazos en la empacadora.', 'Disminuir la carga de toxinas y algas no deseadas que se concentran en el fondo del estanque donde se alimentan los Camarones y Peces y que les causan sabores no esperados despues de que se cosechan y son evaluados en la empacadora.', 'Alta concentración de toxinas y algas no esperadas en el fondo del estanque por el incremento de los depósitos orgánicos en descomposición y que las asimilan los Camarones y Peces al alimentarse.', 'Aplicar 1 Litro de <A HREF="http://www.oriusbiotecnologia.com/2010/productos-soluciones/acuicola/bio-clean-sc" TARGET="_blank"><B><U>BIOCLEAN</U></B></A> por hectárea de superficie en el fondo del estanque utilizando el sistema de flauta 15 a 20 días antes de la cosecha.', 'bioclean', 2),
(50, 'Alta cantidad de subproductos de proceso agroindustrial o de post cosecha o estiércol que necesitan convertirse en Abono Orgánico para evitar descomposición, fermentación, malos olores, lixiviados tóxicos, producción de moscas y de insectos plaga', 'Aplicar 1 Litro de DIGESTOR para 10 Toneladas de subproductos orgánicos. <A HREF="http://www.oriusbiotecnologia.com/el-mejor-abono-organico" TARGET="_blank">Ver</A>', 'Mala disposición y mal manejo de los residuos sólidos orgánicos', 'Aplicarlo al iniciar el proceso con una humedad del material a tratar del 50 al 60% y volteando 2 veces para homogenizar la mezcla. Debe cubrirse con un plástico para incrementar la temperatura, evitar la saturación de agua por lluvia, evitar que se seque la superficie y disminuir incidencia de moscas.', 'digestor', 4),
(51, 'Saturación de los estanques de oxidación con incremento de lodos en el fondo y con incremento de malos olores', 'Recuperar la fracción biológica y limpiar los estanques de toxinas con +CLEAN aplicando 10L/ha de superficie para iniciar y después 350 cc/ha cada día.', 'Muerte de la fracción biológica del estanque anaerobio y de los estanques aerobios por saturación de toxinas y carga orgánica muy alta. ', 'Aplicarlo al iniciar el proceso después de la limpieza del estanque, agregando al ingreso de efluentes los 10 L/ha, y después se aplican gota a gota los 350 cc/ha diluidos en 200 Litros de agua con los efluentes. ', 'maxclean', 4),
(52, 'Saturación de pozos sépticos, limpieza de los tubos de drenaje y malos olores que se devuelven por los tubos de drenaje.', 'Recuperar la fracción biológica y limpiar los estanques de toxinas con +CLEAN aplicando 1 Litro para iniciar y 250 cc/ha cada 15 días.', 'Muerte de la fracción biológica del pozo séptico o incremento de microorganismos anaerobios productores de metano y sulfuros con saturación orgánica por celulosa o papel. ', 'Aplicarlo al iniciar el proceso después de la limpieza del pozo séptico agregando un pequeño chorro a cada sifon, sanitario, lavaplatos, lavamanos, ducha. Se puede diluir el Litro en 10 Litros de agua (un balde). Después se abre la llave del agua y se deja correr el agua para que llegue el +CLEAN al pozo séptico y transite por las tuberías de efluentes.', 'maxclean', 4);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
